<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIAJ50Dj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIAJ50Dj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIAJ50Dj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIAJ50Dj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIAJ50Dj\App_KernelDevDebugContainer([
    'container.build_hash' => 'IAJ50Dj',
    'container.build_id' => '413fa20c',
    'container.build_time' => 1766567807,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIAJ50Dj');
